# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('url', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(max_length=30)),
            ],
        ),
    ]
